server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
spring:  
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/business/**,/personnel/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/BankAccount/**,/credit/**,/producttype/**
        #- id: transaction-service
         # uri: lb://TRANSACTION-SERVICE
          #predicates:
           # - Path=/transaction/**

